### ISSUE TITLE
Process URL which contains IP Address

### ISSUE THREAD

**Issue by JoeDevler** [barseghyanartur/tld#107]
Hello,
i need to process a large list of URLs and split them into components.
Unfortunately some of these URLs contains an ip address, so get this error:

  File "...\venv\lib\site-packages\tld\utils.py", line 504, in get_tld
    domain_parts, non_zero_i, parsed_url = process_url(
  File "...\venv\lib\site-packages\tld\utils.py", line 381, in process_url
    raise TldDomainNotFound(domain_name=domain_name)

res = get_tld(line, as_object=True, **fail_silently=True**)
solve this, but i still cant get any components from URLs.

is there any simple solution to set ip as netloc and get path, query etc?

**Comment by barseghyanartur** [comment]
It depends on the type of error and where does that happen, but you do get the parsed URL back with fail_silently set to True.

Check [this](https://github.com/barseghyanartur/tld/blob/e140056301c02870ffa623c853ce71d6d9b7d26c/src/tld/utils.py#L321).

```python
    # ...
    if not isinstance(url, SplitResult):
        if fix_protocol and not url.startswith(("//", "http://", "https://")):
            url = f"https://{url}"

        # Get parsed URL as we might need it later
        parsed_url = urlsplit(url)
    else:
        parsed_url = url

    # Get (sub) domain name
    domain_name = parsed_url.hostname

    if not domain_name:
        if fail_silently:
            return None, None, parsed_url  # <--- Is this not what you need?
        else:
            raise TldBadUrl(url=url)
    # ...
```

**Comment by JoeDevler** [comment]
thank you for the quick reply.

example:
tld_res = get_tld('https://1.1.1.1/pandas-docs/stable/user_guide/text.html', as_object=True, fail_silently=True)
print(tld_res.parsed_url.path)

AttributeError: 'NoneType' object has no attribute 'parsed_url'

---

o = urlsplit('https://1.1.1.1/pandas-docs/stable/user_guide/text.html')
print(o.hostname + ';' + o.path)

1.1.1.1;/pandas-docs/stable/user_guide/text.html


Did I do something wrong?

**Comment by barseghyanartur** [comment]
You can also try it the other way around, because ``get_tld`` accepts ``SplitResult`` as well as a ``url`` argument type:

```python
from urllib.parse import urlsplit
from tld import get_tld

url_split_result = urlsplit('https://1.1.1.1/pandas-docs/stable/user_guide/text.html')

tld_res = get_tld(url_split_result, as_object=True, fail_silently=True)
```

I hope this helps.
