### ISSUE TITLE
Custom tld names list error

### ISSUE THREAD

**Issue by alealbonico** [barseghyanartur/tld#108]
I need help with my code.

I'm trying to use a custom list with certain non-traditional dns domains in it but while running tests through cicrleci I keep getting source_url related errors such as these ones: 
`AttributeError: type object 'DomainValidator' has no attribute 'source_url'` (if i add source_url to my code it still fails)
`TldIOError: <urlopen error [Errno -2] Name or service not known>` (this one happened when I tried to use version 0.10 of tld to see if I'd encounter the same issue)

I'm using python 2.7 and, except for that last one, all the tests have been done through the latest version of tld.

This is how I edited the tld names list file with some of the domains:
````
...
// ===BEGIN ICANN DOMAINS===

// Not valid traditional DNS domains
bazar
bit
crypto
eth
...
````

This is what the class looks like and how I'm calling it:
````
...
class DomainValidator(BaseMozillaTLDSourceParser):
    uid = 'custom_mozilla'
    local_path = '/myapp/src/Utils/effective_tld_names_custom.dat.txt'


def valid_domain(host):
    try:
        host_tld = tld.get_fld(host, fix_protocol=True, parser_class=DomainValidator)
...
````

**Comment by barseghyanartur** [comment]
Please use the latest version.

**Comment by barseghyanartur** [comment]
@alealbonico:

I'll investigate this.

**Comment by barseghyanartur** [comment]
@alealbonico:

I can't reproduce your issue unfortunately.

Did you make sure you provided a valid `local_path` value?

See a working example [here](https://github.com/barseghyanartur/tld/tree/master/examples/custom_tld_names_source).

**Comment by alealbonico** [comment]
Really sorry I couldn't reply before.
I just checked the examples you left me (thank you so much) and yeah everything seems to be okay.
Maybe there's an issue with some other tld unrelated files in my repo, if I find anything worth analyzing I'll let you know.

**Comment by alealbonico** [comment]
Hi. Turns out the problem was, indeed, the local_path. Some containers were having trouble finding the file because I failed to realise the path was different in them.

If possible, I do think it would be nice to change the error message to something more specific. Nonetheless, thank you for all the help.
