### ISSUE TITLE
result is not expected

### ISSUE THREAD

**Issue by shangliuyan** [barseghyanartur/tld#11]
I use get_tld method, my input arg is "http://leoshang.blogspot.com", but the result is not expected.My code below:

```
>>> res = get_tld("http://leoshang.blogspot.com")
>>> res
leoshang.blogspot.com
```

The result should return "blogspot.com", but the reality return "leoshang.blogspot.com". 
Is there something wrong?

**Comment by barseghyanartur** [comment]
@shangliuyan:

Accoording to the [List of TLD names is taken from Mozilla](https://publicsuffix.org/list/effective_tld_names.dat) blogspot.com is domain extension and thus,  `leoshang.blogspot.com` would be the TLD.
