### ISSUE TITLE
tld v0.12.6 rejects `ZA` as a valid TLD

### ISSUE THREAD

**Issue by bskinn** [barseghyanartur/tld#110]
Python 3.9.7, Debian Linux:

```
>>> import tld
>>> tld.__version__
'0.12.6'
>>> tld.is_tld('za')
False
```

`ZA` shows in the [30 Oct 2021 IANA list of TLDs](https://data.iana.org/TLD/tlds-alpha-by-domain.txt).

**Comment by barseghyanartur** [comment]
Update the tld names to get it fixed. See the docs.

**Comment by bskinn** [comment]
Oh, interesting, I missed that a names update might be needed even after a fresh pip install.

Thanks...sorry to bother!
