### ISSUE TITLE
TLD / FLD error with lambda.us-east-1.amazonaws.com while ok with lambda.us-east-2.amazonaws.com

### ISSUE THREAD

**Issue by frfranck** [barseghyanartur/tld#113]
tld 0.12.6

**Correct:**
parse_tld('https://lambda.us-east-2.amazonaws.com')
=> ('com', 'amazonaws', 'lambda.us-east-2')
get_fld('lambda.us-east-2.amazonaws.com')
=>  amazonaws.com

**Incorrect:**
parse_tld('https://lambda.us-east-1.amazonaws.com')
=> ('us-east-1.amazonaws.com', 'lambda', '')
get_fld('lambda.us-east-1.amazonaws.com')
=> lambda.us-east-1.amazonaws.com

Any feedback would be greetly appreciated.

**Comment by barseghyanartur** [comment]
@frfranck:

Please, check this: https://github.com/barseghyanartur/tld/issues/112

**Comment by frfranck** [comment]
@barseghyanartur 
Ok - thank your for the quick reply

Quite strange that it works for one url and not the other one but with the additional parameter search_private, it provides the correct result in both cases.

**Comment by barseghyanartur** [comment]
@frfranck:

Thanks for reporting this. I think it's time to open a separate FAQ file. :)
