### ISSUE TITLE
Invalid TLD

### ISSUE THREAD

**Issue by osagit** [barseghyanartur/tld#118]
Amazon domains such as :

- canary-dec42bfe74.5gwkqt.c4.kafka-beta.us-east-1.amazonaws.com

gives a bad TLD from tld lib (`tld.get_tld(domain, as_object=True, fail_silently=False, fix_protocol=True)`)

tld : us-east-1.amazonaws.com

**Comment by boogheta** [comment]
Hello,
Why would you think this is a bad TLD?
It is an official TLD registered and listed in the official public suffix list maintained by Mozilla: https://publicsuffix.org/list/public_suffix_list.dat
You can read more about TLDs here: https://publicsuffix.org/

**Comment by osagit** [comment]
Hello, 
Ok, thanks for the links and the quick reply.
