### ISSUE TITLE
Allow custom NAMES_SOURCE_URL value

### ISSUE THREAD

**Issue by vaurdan** [barseghyanartur/tld#12]
Mozilla's MRX is suffering an outage, which makes updating the database impossible:

https://bugzilla.mozilla.org/show_bug.cgi?id=1279952

I think it would be nice if it was possible to force updating using a custom url, from a cloned mozilla-central repo or from an alternative url like `http://hg.mozilla.org/mozilla-central/raw-file/tip/netwerk/dns/effective_tld_names.dat` which has higher availability than `mrx`. Or even use `https://publicsuffix.org/list/public_suffix_list.dat` which seems to be the official list.

Also, I was told in Mozilla's IRC that `mrx` is going to be deprecated soon in favor of drx.mozilla.org, so it's a good idea to change the default.

**Comment by barseghyanartur** [comment]
@vaurdan:

I agree that finally this should implemented. :) I'm adding it to the planned TODOs. Thanks!

**Comment by barseghyanartur** [comment]
[Implemented in](https://github.com/barseghyanartur/tld/tree/feature/62-Introduce-parser-classes). Yet work in progress. Release to follow.

**Comment by barseghyanartur** [comment]
Implemented in 0.11.
