### ISSUE TITLE
terminology problem (TLD != suffix)

### ISSUE THREAD

**Issue by karentamrazyan** [barseghyanartur/tld#120]
This following usage example looks a bit absurd to me:

```
get_tld("http://www.google.co.uk")
# 'co.uk'
```

The problem is that the 'co.uk' part is technically NOT a TLD. The TLD of www.google.co.uk us 'uk'.

**Comment by barseghyanartur** [comment]
Duplicate:

https://github.com/barseghyanartur/tld/issues/95
