### ISSUE TITLE
Possibility to drop py2.7 support

### ISSUE THREAD

**Issue by Yomguithereal** [barseghyanartur/tld#122]
Hello @barseghyanartur, I hope you are alright. I recently internalized tld and suffix related helpers into `ural` codebase because we discovered we need nitpicky stuff that should not be part of a general-purpose library. So I guess you can drop support for py2.7 now if this is convenient to you.

Have a good weekend,

**Comment by barseghyanartur** [comment]
Done. Released in 0.13. 

As a side note, thank you, @Yomguithereal, you have been an awesome contributor throughout the years.
