### ISSUE TITLE
get_tld does not work without http://

### ISSUE THREAD

**Issue by y2kbadbug** [barseghyanartur/tld#13]
I don't know if this should be a feature or bug, however, when trying to use get_tld on a domain like www.google.com instead of http://www.google.com

You get this error:
tld.exceptions.TldBadUrl: Is not a valid URL

**Comment by barseghyanartur** [comment]
@y2kbadbug:

Input is URL, thus - it should be with http.

**Comment by y2kbadbug** [comment]
Is there any other functions to do without the http://?

**Comment by barseghyanartur** [comment]
You can write your own wrapper around it.

```python
from tld import get_tld

def fix_url_protocol(url):
    if not (url.startswith('http://') or url.startswith('https://')):
        url = 'http://{}'.format(url)

def get_tld_from_any(url, **kwargs):
    return get_tld(fix_url_protoco(url), **kwargs)

tld_data = get_tld_from_any(url)
```

**Comment by barseghyanartur** [comment]
@y2kbadbug:

A new optional argument ``fix_protocol`` has been added in [0.7.8](https://pypi.python.org/pypi/tld/0.7.8) to address the issue:

```python
from tld import get_tld

get_tld("www.google.co.uk", fix_protocol=True)
# 'google.co.uk'
```
