### ISSUE TITLE
update-tld-names fails on 0.7.7

### ISSUE THREAD

**Issue by GaretJax** [barseghyanartur/tld#14]
This release introduces a relative import for a non-package (when installed).

```
# /usr/local/bin/update-tld-names
Traceback (most recent call last):
  File "/virtualenv/bin/update-tld-names", line 3, in <module>
    from ..commands.update_tld_names import main
ValueError: Attempted relative import in non-package
```

**Comment by barseghyanartur** [comment]
@GaretJax:

Thanks for reporting this. I'll fix it ASAP (probably within two days). Pull requests are welcome too.

**Comment by GaretJax** [comment]
There you go https://github.com/barseghyanartur/tld/pull/15 ;-)

Thanks for open sourcing this tool!

**Comment by barseghyanartur** [comment]
@GaretJax: Thank you.
