### ISSUE TITLE
Protocol relative url doesn't need to be fixed

### ISSUE THREAD

**Issue by tomako** [barseghyanartur/tld#20]
It is safe to use the `fix_protocol` parameter even when the url has proper protocol:
`>>> get_tld("http://www.google.co.uk")`
`'google.co.uk'`
`>>> get_tld("http://www.google.co.uk", fix_protocol=True)`
`'google.co.uk'`

But not in case of protocol relative url though it is valid for `urlparse`
`>>> get_tld("//www.google.co.uk")`
`'google.co.uk'`
`>>> get_tld("//www.google.co.uk", fix_protocol=True)`
`Traceback (most recent call last):`
`  File "<input>", line 1, in <module>`
`  File "/home/tomako/worx/poderio/poderio-cat/pyve/lib/python3.5/site-packages/tld/utils.py", line 178, in get_tld`
`    raise TldBadUrl(url=url)`
`tld.exceptions.TldBadUrl: Is not a valid URL https:////www.google.co.uk!`

**Comment by barseghyanartur** [comment]
@tomako:

Thanks for reporting this!

Fixed in version 0.7.10.
