### ISSUE TITLE
How to recognize tlds llike 'xn--fiqs8s' rather than other language ?

### ISSUE THREAD

**Issue by LosSherl** [barseghyanartur/tld#23]
What could I do if I want to get tld from '*****.xn--fiqs8s' without exception?

**Comment by Yomguithereal** [comment]
PR opened.

**Comment by barseghyanartur** [comment]
Solved in branch [v0.8](https://github.com/barseghyanartur/tld/tree/v0.8). To be released in 0.8.

**Comment by barseghyanartur** [comment]
Released in 0.8.
