### ISSUE TITLE
Mixed up changelog entries?

### ISSUE THREAD

**Issue by sebix** [barseghyanartur/tld#24]
Looking at the [differences between 0.7.9 and 0.7.10](https://github.com/barseghyanartur/tld/compare/0.7.9...0.7.10#diff-de0a9b67ffe2874a076b5fdb15bad484) we can see that the changelog entry of version 0.7.6 has been updated with exactly the content I would expect for 0.7.10.

**Comment by barseghyanartur** [comment]
@sebix:

Done. Thanks again!
