### ISSUE TITLE
Issue with resolving valid tlds

### ISSUE THREAD

**Issue by kirsn** [barseghyanartur/tld#3]
Code for test: https://gist.github.com/kirsn/c920bf25ddfa8810364a,
View the comment for details of valid tlds which are excluded.

**Comment by danielsamuels** [comment]
Yup, we're having this issue with our .media TLD. Crazy that this hasn't been fixed, it makes the library unusable.

**Comment by barseghyanartur** [comment]
@danielsamuels:

It's solved by updating the tld names.

**Comment by barseghyanartur** [comment]
Version 0.7.3 contains updated TLD source file. Either doing that or using the "update-tld-names" command from terminal would solve the problem.

**Comment by kirsn** [comment]
Confirmed that it works now. Thanks for fixing.
