### ISSUE TITLE
Problems with version 0.7.3 domains .local

### ISSUE THREAD

**Issue by pollitosabroson** [barseghyanartur/tld#5]
I have a problem with the version 0.7.3, the reason of this one is because they eliminated the domains .local in the version 0.73 since in the version 0.7.2 if I can test with the domain .local 

To The moment to do constant tests sea ael following I wander 

``` bash
       TldDomainNotFound: Domain sso.local didn't match any existing TLD name

```

**Comment by barseghyanartur** [comment]
@pollitosabroson:

Ufortunately, this is how it is. You may apply custom checks before passing it to `tld`.
