### ISSUE TITLE
What to do with url containing only the tld?

### ISSUE THREAD

**Issue by Yomguithereal** [barseghyanartur/tld#51]
@barseghyanartur I have a question: what should we do with urls such as:

```
http://cloud.fedoraproject.org
```

where the whole domain string is just a tld?

I know those cases are edge and probably illegal but they do work in browsers. Currently return values for those cases are not consistent (either a false or empty or return value).

I propose we return the the tld and blank the domain/subdomain etc.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

I agree. Let's just return the `tld`. 

In case of an object `domain`/`subdomain` properties shall be blank. Perhaps the `fld` shall in this case be just equal to `tld`.

**Comment by Yomguithereal** [comment]
I'll draft a PR to support this when I can.
