### ISSUE TITLE
test_[1,2]_update_tld_names_* seems to rely on network

### ISSUE THREAD

**Issue by flokli** [barseghyanartur/tld#54]
We run the tests in an isolated phase without network:

```
======================================================================
FAIL: test_1_update_tld_names (tld.tests.test_core.TestCore)
Inner.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/tld-0.9.3/src/tld/tests/base.py", line 30, in inner
    result = func(self, *args, **kwargs)
  File "/build/tld-0.9.3/src/tld/tests/test_core.py", line 312, in test_1_update_tld_names
    self.assertTrue(res)
AssertionError: False is not true
======================================================================
FAIL: test_2_update_tld_names_module (tld.tests.test_commands.TestCommands)
Inner.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/tld-0.9.3/src/tld/tests/base.py", line 30, in inner
    result = func(self, *args, **kwargs)
  File "/build/tld-0.9.3/src/tld/tests/test_commands.py", line 39, in test_2_update_tld_names_module
    self.assertEqual(res, b'True')
AssertionError: b'<urlopen error [Errno -2] Name or service not known>' != b'True'

----------------------------------------------------------------------
```

**Comment by barseghyanartur** [comment]
@flokli:

Yes it does, since that's what it's supposed to do - pull the latest database from Mozilla's sources.

**Comment by flokli** [comment]
I'm just not sure whether it's good practice to do that inside a unit test - during software packaging, it's very common to run these tests in an isolated environment during packaging, so unit tests would need to mock network access.

Is that code supposed to be run from a `tld` source checkout, to update the `src/tld/res/effective_tld_names.dat.txt` file in-place? In that case, I'd more consider it release tooling for `tld` itself.
Or is it a valid update mechanism that can even be used for consumers of the library?

**Comment by barseghyanartur** [comment]
@flokli:

It's a valid update mechanism. It's recommended to run it every now and then (like, once a month or so). But I understand your point.

What do you suggest?

Eventually, I could make the failing tests conditional (environment setting, False by default) or mock (by default, but use network if environment setting is set to True).

**Comment by flokli** [comment]
Instead of shelling out to `src/tld/commands/update_tld_names.py` / `src/tld/bin/update-tld-names`, I'd just use `tld.commands.update_tld_names.main` (or `tld.utils.update_tld_names`) in the test directly - it's unit tests after all, not integration tests, so we shouldn't shell out to binaries there.

Inside the test, you could then just mock away the urllib call, similar to [here](https://stackoverflow.com/a/19204230) - and wouldn't need to add support for magic environment variables. In that case, the tests would still make sure the logic works, and you can run it manually against a real endpoint when you want to actually update the list. 

Side question: can't you use `entry_points…console_scripts` in `setup.py` to let setuptools generate the wrapper for `update-tld-names`? This would allow to remove some indirection boilerplate, too…

Let me know if I should file a PR, suggesting these changes or whether you want to go on with that :-)

**Comment by barseghyanartur** [comment]
@flokli:

Regarding using `tld.utils.update_tld_names` directly - that's already done in `test_core`. So, I guess I'll just rely on environmental variable. However, I do not want to drop testing commands, but rather skip those tests if needed and add an additional test using mock (which will be executed in any case).

Regarding your side question. Sure, please make a pull request.

**Comment by barseghyanartur** [comment]
@flokli: Ping.

**Comment by flokli** [comment]
I opened a PR with the suggested simplifications in https://github.com/barseghyanartur/tld/pull/55.

**Comment by barseghyanartur** [comment]
@flokli:

This is likely to be fixed in the upcoming version.

**Comment by barseghyanartur** [comment]
Done in 0.9.4.
