### ISSUE TITLE
No module named 'tld'

### ISSUE THREAD

**Issue by analyticsftw** [barseghyanartur/tld#56]
Hi there, using Python 3.7 and installed tld over pip but whenever I try 
`from tld import get_tld`
I systematically get a "ModuleNotFoundError: No module named 'tld'"

Please advise.

**Comment by barseghyanartur** [comment]
Not sure. Builds are passing https://travis-ci.org/barseghyanartur/tld

**Comment by barseghyanartur** [comment]
@analyticsftw:

Are you still having this issue? What system do you use?

**Comment by analyticsftw** [comment]
Thanks for following up, I upgraded pip and discovered I had a freak dependency error.
All went great after the update :-)
Raspberry Pi 3 / Debian Stretch / Python 3.7
