### ISSUE TITLE
Domain not correctly recognised

### ISSUE THREAD

**Issue by contrivable** [barseghyanartur/tld#63]
Hi,
today I pulled tld==0.9.7 (via conda) and it seems domains are not always correctly recognised.
I run:
`python -c "import tld; domain = tld.get_tld('http://blogspot.com', as_object=True).domain; print(f':{domain}:')"`
What I see:
`::`
What I expect to see (and see when reverting to tld==0.9.6):
`:blogspot:`

**Comment by Yomguithereal** [comment]
Hello @contrivable. That is because #51 was closed. `blogspot.com` is actually a tld so it has no domain per se. But I see how this could be confusing. @barseghyanartur is this ok? Should we set domain = tld in this case?

**Comment by barseghyanartur** [comment]
@Yomguithereal 

Let's do that.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Would you have time to prepare a PR?

**Comment by Yomguithereal** [comment]
Maybe next week.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Thanks a lot!

@contrivable:

Issue is closed. PyPI release will follow shortly.

**Comment by barseghyanartur** [comment]
Released with 0.9.8.
