### ISSUE TITLE
Consider moving to google/pygtrie

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/tld#69]
Consider moving to google/pygtrie

**Comment by Yomguithereal** [comment]
Why though? Would this make things easier for serialization? The lib's current Trie is tailored for your use case (regarding wildcards and public/private etc.).

**Comment by barseghyanartur** [comment]
@Yomguithereal:

It's just something to consider and certainly try (in a branch), as a potential improvement (speed up). If that one works remarkably faster, it wouldn't be wise not to. I haven't studied that library well enough to tell whether it would make serialisation simpler or not, but that would be a minor and doable thing anyway.
