### ISSUE TITLE
Type hints & 3.5 support

### ISSUE THREAD

**Issue by Yomguithereal** [barseghyanartur/tld#72]
Hello @barseghyanartur,

while I appreciate the interest of type hints in python you dropped support for python 3.5 doing so. Was this your intention?

**Comment by barseghyanartur** [comment]
Ah, Python 3.5 is not yet EOL, indeed. How long will you be using it? :)

**Comment by Yomguithereal** [comment]
I personally don't use it but a lot of our servers still run 3.5 and a lot of my colleagues machines still come packing a default 3.5. But isn't there a way in python to strip type hints for release? Or was your intention to provide those typings to consumers of the library for convenience? Isn't there a separate file declaration system existing in python such as there is in Typescript?

**Comment by barseghyanartur** [comment]
@Yomguithereal:

There is a type hint declaration for Python 2.7 and 3.5 as well, although not as nice as for 3.6. But fair enough. Python 3.5 support will be back. :)

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Version 0.11.3 has targeted dists working on Python 3.5. I need to still figure out how to make things working on Python 3.6 and up (since that part is now broken on 0.11.1, not the code, but the distribution thinks 0.11.3 is not suitable for py36 and up; perhaps I need to repeat the trick I did for py35 distribution to py36, py37 and py38). Anyway, since there were no changes at all (since 0.11.1 release), it's safe to say, most recent versions of `tld` do run on all python versions.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

So, I now build distribs for all targeted versions, but somehow in Python 3.5 environment `pip install tld` does not pick the latest release (somehow thinks it's not suitable). However, if grabbing download link from PyPI just works.

```bash
pip install https://files.pythonhosted.org/packages/fa/dd/a98039a556118e68bb7091248293e51f3c28b03f6d3f389977513a127d05/tld-0.11.5-py35-none-any.whl
```

Any help here is appreciated. :)

**Comment by barseghyanartur** [comment]
One guess would be to soften conditional `python_requires` value to always be `>=3.5`. I'll try that.

**Comment by Yomguithereal** [comment]
Python packaging is such a mess :)

**Comment by Yomguithereal** [comment]
Also, and I know I am bothersome: is this still compatible with py2.7 :) (and believe me I would love not being the person asking this question)?

**Comment by barseghyanartur** [comment]
At the moment I'm converting things to python 2.7 on the fly and replacing some things with sed. Then run tests against python 3.5. I'm pretty sure it will work. I'll make a python 2.7 distro as well.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Done.

**Comment by Yomguithereal** [comment]
Thank your very much @barseghyanartur. Sorry for the hassle it must have been. I will upgrade my dependent libraries as soon as possible.
