### ISSUE TITLE
effective_tld_names-2015-07-19.dat.txt has executable bits set

### ISSUE THREAD

**Issue by sebix** [barseghyanartur/tld#75]
The file `src/tld/res/old/effective_tld_names-2015-07-19.dat.txt` in verison 0.11.9 has the executable bit set, but I see no reason why it needs that.

**Comment by barseghyanartur** [comment]
@sebix:

That's accidental. I'll fix that. Thanks!

**Comment by barseghyanartur** [comment]
Fixed in 0.11.10.
