### ISSUE TITLE
Python 2 compatibility is broken by typing module

### ISSUE THREAD

**Issue by heroesm** [barseghyanartur/tld#76]
There is no typing module in standard library of Python 2; to use typing in Python 2 , the backport pypi module typing should be added to install_requires explicitly:

https://pypi.org/project/typing/

https://github.com/barseghyanartur/tld/blob/master/setup.py#L79

Currently, tld can be installed successfully in Python 2 environment, but when you try to import it:
`ImportError: No module named typing`
is raised.

Add requirment 'typing;python_version<"3.5"' to setup.py might fix this issue.

**Comment by barseghyanartur** [comment]
Fixed in 0.11.10.

**Comment by barseghyanartur** [comment]
Also, added to the testing matrix.

Results here: https://travis-ci.org/barseghyanartur/tld/builds/647048934?utm_source=github_status&utm_medium=notification
