### ISSUE TITLE
TLD parse Error

### ISSUE THREAD

**Issue by ehaoxiongdiycw** [barseghyanartur/tld#78]
tld==0.11.10

```python
In [17]: get_tld("http://prod.www-fastly-com.map.fastly.net")
Out[17]: 'map.fastly.net'

In [18]: get_tld("http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/")
Out[18]: 'cn-north-1.elb.amazonaws.com.cn'
```

**Comment by Yomguithereal** [comment]
Can you explain the issue? This is not obvious. Have you tried updating the tld list? Those might be more recent than the default list shipped with the lib.

**Comment by barseghyanartur** [comment]
In the list of mozilla, the ``*.elb.amazonaws.com.cn`` is a TLD.

**Comment by ehaoxiongdiycw** [comment]
> In the list of mozilla, the `*.elb.amazonaws.com.cn` is a TLD.
> 
> ```
> cat effective_tld_names.dat.txt | grep "amazonaws.com.cn"
> *.compute.amazonaws.com.cn
> cn-north-1.eb.amazonaws.com.cn
> cn-northwest-1.eb.amazonaws.com.cn
> *.elb.amazonaws.com.cn
> s3.cn-north-1.amazonaws.com.cn
> ```
> 
> One way of dealing with that is to set the `search_private` to False.
> 
> ```python
> get_tld("http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/", search_private=False)
> ```

I updated the tld list, find the effective_tld_names.dat.txt, the cotent is same with you.

But when I try your code, Exception happened, and i don't kwon how to deal with it.

```
In [11]: get_fld("http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/", search_private=False)
---------------------------------------------------------------------------
TldDomainNotFound                         Traceback (most recent call last)
<ipython-input-11-0c3247922a09> in <module>
----> 1 get_fld("http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/", search_private=False)

~/py-venv/python3.7/lib/python3.7/site-packages/tld/utils.py in get_fld(url, fail_silently, fix_protocol, search_public, search_private, parser_class, **kwargs)
    430         search_public=search_public,
    431         search_private=search_private,
--> 432         parser_class=parser_class
    433     )
    434

~/py-venv/python3.7/lib/python3.7/site-packages/tld/utils.py in process_url(url, fail_silently, fix_protocol, search_public, search_private, parser_class)
    374             return None, None, parsed_url
    375         else:
--> 376             raise TldDomainNotFound(domain_name=domain_name)
    377
    378     if len_domain_parts == tld_length:

TldDomainNotFound: Domain www-dida-313720269.cn-north-1.elb.amazonaws.com.cn didn't match any existing TLD name!
```

**Comment by barseghyanartur** [comment]
Add ``fail_silently`` argument set to ``False``.

```python
get_tld("http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/", search_private=False, fail_silently=True)
```

**Comment by barseghyanartur** [comment]
@ehaoxiongdiycw:

Yes. Empty result list you get, because you didn't want to have exceptions. Perhaps, you need to come up what do you want first? Because honestly, I don't get what's your issue is.

**Comment by ehaoxiongdiycw** [comment]
sorry, i click uncorrectly.

**Comment by ehaoxiongdiycw** [comment]
@barseghyanartur ok, I try to describe.

if `com.cn` is a TLD, then 'xxxxxx.com.cn`'s TLD shoud be `com.cn`. 

In the list of mozilla, the `*.elb.amazonaws.com.cn` is a TLD. When I use the param `search_private=False`, `*.elb.amazonaws.com.cn`  will be ignore and `com.cn` is the TLD for `http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/`.

So, when i exec the code, `tld = get_tld("http://www-dida-313720269.cn-north-1.elb.amazonaws.com.cn/", search_private=False)`, the `tld` i want is `com.cn`, without Exception and None Type.

**Comment by barseghyanartur** [comment]
@ehaoxiongdiycw:

OK, this is possible, although since we depend on the Mozilla's list of TLDs, there's no way you would get that. However, you could pick the Mozilla's list, make one of your own, define a custom  parser as shown [here](https://github.com/barseghyanartur/tld#custom-list-of-tld-names) and always pass it to the ``get_tld`` function as ``parser_class`` argument.

**Comment by ehaoxiongdiycw** [comment]
Got it. Thank you. @barseghyanartur
