### ISSUE TITLE
Support domains as input (sans scheme)

### ISSUE THREAD

**Issue by rosstex** [barseghyanartur/tld#81]
This is just a feature request, as I had a dataset containing just domain names (no "http(s)://") and discovered the API wouldn't support it directly. It would be awesome to support inputting plain domains as well!

**Comment by rosstex** [comment]
nvm, just saw "fix_protocol=True". I wouldn't say the inputs are "broken", but this works :)

**Comment by barseghyanartur** [comment]
Yes, setting `fix_protocol` to `True` should do the trick. Closing this.
