### ISSUE TITLE
Why the fld of url "ch-asia-northeast2.storage.googleapis.com" is "storage.googleapis.com" rather than "googleapis.com" ?

### ISSUE THREAD

**Issue by Panjks** [barseghyanartur/tld#82]
Why the fld of url "ch-asia-northeast2.storage.googleapis.com" is "storage.googleapis.com" rather than "googleapis.com" ?

**Comment by imShara** [comment]
And
```
get_tld('a.jdevcloud.com', fix_protocol=True, as_object=True).fld
'a.jdevcloud.com'
```
There is no whois for `jdevcloud.com`, but regular `com`
Listed here [effective_tld_names.dat.txt](https://github.com/barseghyanartur/tld/blob/80a7040e4d0021a66ab934a9a664a26578e5accf/src/tld/res/effective_tld_names.dat.txt)

**Comment by barseghyanartur** [comment]
jdevcloud.com is listed as a [private](https://github.com/barseghyanartur/tld/blob/80a7040e4d0021a66ab934a9a664a26578e5accf/src/tld/res/effective_tld_names.dat.txt#L10660) TLD. This library just parses the public suffix and gives you the result back. For questions regarding jdevclould.com being alive or not, contract public suffix website.
