### ISSUE TITLE
domain ending in . not recognized

### ISSUE THREAD

**Issue by rosstex** [barseghyanartur/tld#83]
I'm parsing a series of request logs from a web crawl, and one of the URLs has a domain that surprisingly ends in a period, 'https://www.pendleton-usa.com./etc'. Web browsers seem to handle this request fine, but TLD crashes with:

`Domain pendleton-usa.com. didn't match any existing TLD name!`

Since such domains work as standard DNS queries, perhaps they should be supported by this library too.

**Comment by barseghyanartur** [comment]
I'll dive into that. If it's supported by python built-ins we rely on, it will be solved.

**Comment by barseghyanartur** [comment]
Fixed in 0.12.1.
