### ISSUE TITLE
LICENSE_MPL_1.1.txt is missing in pypi tarballs

### ISSUE THREAD

**Issue by suve** [barseghyanartur/tld#84]
When downloading `tld` from pypi, the tarballs contain `LICENSE_GPL2.0.txt` and `LICENSE_LGPL_2.1.txt`, but the `LICENSE_MPL_1.1.txt` file is missing.

**Comment by barseghyanartur** [comment]
That's because such classifier does not exist on PyPI side.

**Comment by barseghyanartur** [comment]
Sorry, just checked, it has been added. I'll add that. Thanks.

```License :: OSI Approved :: Mozilla Public License 1.1 (MPL 1.1)```

**Comment by barseghyanartur** [comment]
Fixed in 0.12.2.
