### ISSUE TITLE
ImportError: cannot import name SplitResult

### ISSUE THREAD

**Issue by zhangjuynag96** [barseghyanartur/tld#87]
![image](https://user-images.githubusercontent.com/37923854/81653028-13072880-9467-11ea-9709-c850229d6b09.png)

**Comment by zhangjuynag96** [comment]
In response to this problem, I modified your code, but it does not apply to other friends. In python2.7.6 version under linux, it is not suitable for importing SplitResult method using urllib.parse and six.moves.urllib_parse, so I use urlparse to import, and then it can run normally. And your library is very easy to use, forgive me for my crappy English, because it is machine-turned.

**Comment by barseghyanartur** [comment]
I'll check it. Thanks for reporting. Python 2.7 is supported in a very limited way and is subject to a total deprecation any time soon. In the meantime, use Python 3.6 if you can.
