### ISSUE TITLE
Include py.typed so Mypy can know the types are available.

### ISSUE THREAD

**Issue by cbowdon** [barseghyanartur/tld#88]
Could you please include an empty `src/tld/py.typed` file in the next release? This would allow Mypy to use the type annotations that you've defined, and save me having to write a stub. :)

**Comment by barseghyanartur** [comment]
@cbowdon:

Done in branch [mypy](https://github.com/barseghyanartur/tld/tree/mypy). However, I'm getting some errors which I did get in past when running mypy, but though they likely to be fixed by now. Could you check and see if you can avoid them (better than simply adding `# type: ignore`?

**Comment by barseghyanartur** [comment]
Released in 0.12.2.

**Comment by cbowdon** [comment]
Thank you!
