### ISSUE TITLE
Add is_tld() function

### ISSUE THREAD

**Issue by april** [barseghyanartur/tld#9]
It would be nice to have a convenience function called .is_tld() that simply returns True if something is a TLD and False if it isn't.  Currently I use `some_tld is in tld.get_tld_names()`, but it doesn't feel the most Pythonic.

Not a big deal either way, just thought I'd ask.  :)

**Comment by barseghyanartur** [comment]
@marumari:

I'm adding it to the TODOs. Thanks!

**Comment by marumari** [comment]
Thanks, much appreciated!

**Comment by Yomguithereal** [comment]
I can make a PR about that soon. @barseghyanartur would this help you? Or is there already some work done towards this?

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Not yet, so, please, do.

**Comment by barseghyanartur** [comment]
Implemented in 0.9.3.
