### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by nabulator** [barseghyanartur/tld#96]
Arch has recently moved to[ Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) but this lib is still on 3.8 (in pip at least). 
Looking quickly through the new features, it looks like relevant functions were removed or changed (mostly debugging features I think). I'm not sure what is required but if it's something like running the tox tests I can help out with that.

**Comment by barseghyanartur** [comment]
@nabulator:

Done in [0.12.4](https://pypi.org/project/tld/0.12.4/#files).
