### ISSUE TITLE
Incorrectly extracted TLD

### ISSUE THREAD

**Issue by HugooB** [barseghyanartur/tld#99]
I think I found this little bug:

```python
import tld

url = "http://www-weekend-at-prod.platform.mediengruppe.at.pr-1539-vmr5j3y-mklkfvg2fby2e.eu-2.platformsh.site"
print(tld.get_tld(url, as_object=True).tld
```

results in `'eu-2.platformsh.site'`, this should be `site`

**Comment by Yomguithereal** [comment]
Hello @HugooB, as per this [line](https://github.com/barseghyanartur/tld/blob/master/src/tld/res/effective_tld_names.dat.txt#L12881) of the suffix liste it seems the correct result is indeed `eu-2.platformsh.site`.

**Comment by HugooB** [comment]
Ah, did not expected that, thanks for letting me know ;)
